#!/bin/csh -f
##############################################################################
#	Job for tao graphic output with GMT 3.0
#	Daniel Garcia-Castellanos, 1994-1996.
##############################################################################
#Syntax:  tao.gmt.job <modelname> <xmin> <xmax> <ymin> <ymax> <switch_sea> 
#			<switch_rheo>
##############################################################################
#Note that:
# -This script uses bc unix command as a calculator. 
# -<xmin> <xmax> must be inside x range defined in .PRM parameters file.
##############################################################################

#Setting up variables:

unalias bc

set model	= $argv[1]
set Lx 		= `echo $3 - $2 | bc`
if ( Lx != 0 ) then
	set xmin	= $2
	set xmax	= $3
	set ymin	= $4
	set ymax	= $5
else
	set xmin	= 50
	set xmax	= 300
	set ymin	= -8000
	set ymax	= 5000
endif
set ps   	= $model.ps

set yminkm 	= `echo $ymin / 1000 \* \(-1\) | bc -l` 
set ymaxkm 	= `echo $ymax / 1000 \* \(-1\) | bc -l` 
set yminkmcr	= 40
set ymaxkmcr	= 33
set region	= $xmin/$xmax/$ymin/$ymax
set numcols 	= `awk '(NR==4) {print NF; exit;}' $model.pfl`
set dens 	= `awk '(NR==2) {print $0; exit;}' $model.pfl`



#geometry:
set graph_width = 15
set graph_height = ` echo $graph_width "*3*(-" $ymin "+" $ymax ") / 1000 / ("$xmax - $xmin\) | bc -l`

psbasemap -JX$graph_width/-$graph_height -R$xmin/$xmax/$ymaxkm/$yminkm \
	-Ba50f10:"distancia (km)":/5f1:"profundidad (km)                   .":nEW -K -X3 -Y7 -P > $ps
psbasemap -JX$graph_width/$graph_height -R$xmin/$xmax/$ymin/$ymax -K -O -B::/::neW		>> $ps

invertfile $model.pfl > $model.2.tao.gmt.tmp

#awk '{if (substr($0,1,1)!="#") print $1, $2/1000}' $model.grv_mod | psxy -JX -R -M -O -K -W10	>> $ps 
psxy $model.pfl -JX -R -O -K -W10	>> $ps

set col = 3
while ($col <= $numcols)
	awk '{print $1, $col}' col=$col $model.pfl > $model.0.tao.gmt.tmp
	awk '{print $1, $(col-1)}' col=$col $model.2.tao.gmt.tmp >> $model.0.tao.gmt.tmp

	if ($dens[$col] > 2500) then
		#set color = $color_basement
	else
		#set color = $color_sediment
	endif
	
	if ($col == 3) then
		set line = 1
	else
		set line = 1
	endif

	psxy $model.0.tao.gmt.tmp -JX -R -O -K -L -M -W$line	>> $ps
	set col = `echo $col + 1 | bc`
end
pstext -JX -R -N -O -K <<END>>$ps
	250	-13000	12 0 0 2	2800 kg·m@+-3@+
	155	-5000	12 0 0 2	2800 kg·m@+-3@+
	210	300	12 0 0 2	2300 kg·m@+-3@+
	220	-21000	12 0 0 2	3300 kg·m@+-3@+
END




set graph_height = ` echo $graph_width "*3*(-" $yminkmcr "+" $ymaxkmcr ") / ("$xmax - $xmin\) | bc -l`
awk '{print $1, $(NF-1)/1000+35}' $model.xzt | \
	psxy -JX$graph_width/$graph_height -R$xmin/$xmax/$ymaxkmcr/$yminkmcr \
	-Ba50f10:"Distancia (km)":/5f1:"":SEW \
	-Y-2.5 -W10 -O -K >> $ps






#Gravity Anomaly graphic:
if (-r $model.xg) then 
	psbasemap -JX$graph_width/4.5 -R$xmin/$xmax/-69.99/60 -Y9 -O -K \
		-B/g20ew\
		>> $ps
	awk '{if (NR>=3) print $1, $2}' $model.xg \
		| psxy -JX -R$xmin/$xmax/-70/60 -W10to -O -K \
		-Ba50f10/a20f20:"anom. Bouguer (mGal)":W\
		>> $ps
	awk '{if (NR>=3) print $1, $3}' $model.xg \
		| psxy -JX -R$xmin/$xmax/-7/6 -W10ta -O \
		-B/a2f1:"anom. geoidal (m)":E \
		>> $ps
endif


rm -f  $model.*.tao.gmt.tmp

