#!/bin/csh
##############################################################################
#	Job for tao graphic output with GMT 3.0
#	Daniel Garcia-Castellanos, 1994-1996.
#
#Syntax:  tao.gmt.job <modelname> <xmin> <xmax> <ymin> <ymax> 
#
#Note that:
# -This script uses bc unix command as a calculator. 
# -<xmin> <xmax> must be inside x range defined in .PRM parameters file.
#
#Output contents:
# From top to bottom: Temperature & crust geometry; Model section; Basin blow
# up; Stress and Te.
##############################################################################




#Setting up variables:

set model	= $argv[1]

set numcols 	= `awk '(NR==4) {print NF}' $model.pfl`
set ps   	= $model.ps
set numhorizs 	= `echo $numcols - 1 | bc -l` 
set switch_sea = $6
set switch_rheo = $7
set color_sea = 100/150/255

set color_basement = 40/120/30
set d_red 	= `echo 140 / 25  | bc ` 
set d_green 	= `echo 140 / 25  | bc ` 
set d_blue	= `echo 60 /  25   | bc ` 

#echo $d_red $d_green $d_blue

#Intermidiate files:



gmtset LABEL_FONT_SIZE 17 HEADER_FONT_SIZE 17 BASEMAP_FRAME_RGB 255/255/200 PAGE_COLOR 0/0/0

#BLOW UP:
#
set xmin = 150
set xmax = 290
set ymin = -2000
set ymax = 1000
set yminbasam = $ymin
set yminkm 	= `echo $ymin /1000 | bc -l` 
set ymaxkm 	= `echo $ymax /1000 | bc -l` 
set region	= $xmin/$xmax/$ymin/$ymax
echo  $xmax $yminbasam > $model.basement.xz.tmp
echo  $xmin $yminbasam >> $model.basement.xz.tmp
cp $model.basement.xz.tmp $model.pru4.tmp
awk   '{print $1, $2}' $model.pfl >> $model.basement.xz.tmp
invertfile $model.pfl > $model.pru2.tmp
echo  $xmin 0 >> $model.pru4.tmp
echo  $xmax 0 >> $model.pru4.tmp

set graph_width = 5.2

psbasemap -JX$graph_width/2.3 -R$xmin/$xmax/$yminkm/$ymaxkm \
	-Ba50f10/1f.5:"(km)":nSeW \
	-K -Y4.5 -X2.1 -P 					> $ps
psxy  -JX -R$xmin/$xmax/$ymin/$ymax -K -O 	<<END		>> $ps
END

#Draws surface:
#cat $model.pru2.tmp | awk '{print $1, $3}' | cat $model.pfl - | \
#	psxy -JX -R -O -M -L -K 				>> $ps

#Draws Sea:
psxy $model.pru4.tmp -JX -R -O -K -L -G$color_sea 		>> $ps

#Draws basement:
psxy $model.basement.xz.tmp -JX -R -O -K -L -G$color_basement 	>> $ps

set col =  3
while ($col <= $numcols)
	echo $col | \
		cat - $model.pfl | \
		awk '{if (NR==1) colawk=$1; else print $1, $colawk}' > $model.pru.tmp
	set colant = `echo $col - 1 | bc`
	echo $colant | \
		cat - $model.pru2.tmp | \
		awk '{if (NR==1) colawk=$1; else print $1, $colawk}' >> $model.pru.tmp

	set Rcolor = `echo \($col - 2\) \* $d_red   + 120 | bc -l`
	set Gcolor = `echo \($col - 2\) \* $d_green + 105 | bc -l`
	set Bcolor = `echo \($col - 2\) \* $d_blue  + 30  | bc -l`
	set color = $Rcolor/$Gcolor/$Bcolor
	set width = 1
	#if ($col == 5 || $col == 6) set color = $color_basement
	#if ($col == 5 || $col == 6) set width = 10
	psxy $model.pru.tmp -JX -R -O -K -M -L -G$color  -W$width/0				>> $ps
	rm -f $model.pru.tmp
	set col = `echo $col + 1 | bc`
end
pstext	-JX	-R  -O 	-K -W0	-G255							<< END	>> $ps
	$xmax	-1900	16  0   1  3	c) 
END
psbasemap -JX -R -Bnsew -F255/0/0 -K -O								>> $ps
if (-r $model.CMP) awk '{print ($1,$2)}' $model.CMP | psxy -JX -R -O -K -M -W4/230/50/50 	>> $ps
if (-r $model.FIT) awk '{print ($1,$2)}' $model.FIT | psxy -JX -R -O -K -St.08 -G255/150/150 -M -W4/255/150/150 >> $ps




#
#TRUE scale PROFILE:

set graph_width = 6.7
set vert_exagg = 1
set xmin	= 100
set xmax	= 300
set ymin	= -15000
set ymax 	= 5000
set yminbasam = -15000
set yminkm 	= `echo $yminbasam /1000 | bc -l` 
set ymaxkm 	= `echo $ymax /1000 | bc -l` 
set graph_height = ` echo $graph_width "* " $vert_exagg " * (-" $yminbasam "+" $ymax ") / 1000 / ("$xmax - $xmin\) | bc -l`
echo  $xmax $yminbasam > $model.basement.xz.tmp
echo  $xmin $yminbasam >> $model.basement.xz.tmp
awk   '{print $1, $2}' $model.pfl >> $model.basement.xz.tmp



psbasemap -JX$graph_width/$graph_height -R$xmin/$xmax/$yminkm/$ymaxkm \
	-Ba50f10:Distance\ \(km\):/10f5:"Elev. (km)":nSeW \
	-K -X-1 -Y3 -O >> $ps
psxy  -JX -R$xmin/$xmax/$yminbasam/$ymax -K -O 	<<END>> $ps
END

#Draws Sea:
psxy $model.pru4.tmp -JX -R -O -K -L -G$color_sea >> $ps

#Draws basement:
psxy $model.basement.xz.tmp -JX -R -O -K -L -G$color_basement 					>> $ps


set col =  3
while ($col <= $numcols)
	echo $col | \
		cat - $model.pfl | \
		awk '{if (NR==1) colawk=$1; else print $1, $colawk}' > $model.pru.tmp
	set colant = `echo $col - 1 | bc`
	echo $colant | \
		cat - $model.pru2.tmp | \
		awk '{if (NR==1) colawk=$1; else print $1, $colawk}' >> $model.pru.tmp

	set Rcolor = `echo \($col - 2\) \* $d_red   + 120 | bc -l`
	set Gcolor = `echo \($col - 2\) \* $d_green + 105 | bc -l`
	set Bcolor = `echo \($col - 2\) \* $d_blue  + 30  | bc -l`
	set color = $Rcolor/$Gcolor/$Bcolor
	set width = 1
	#if ($col == 5 || $col == 6) set color = $color_basement
	#if ($col == 5 || $col == 6) set width = 6
	psxy $model.pru.tmp -JX -R -O -K -M -L -G$color  -W$width/0			>> $ps
	rm -f $model.pru.tmp
	set col = `echo $col + 1 | bc`
end
if (-r $model.CMP) awk '{print ($1,$2)}' $model.CMP | psxy -JX -R -K -O -M -W4/230/50/50 	>> $ps
pstext	-JX	-R  -O 	-K -W0	-G255							<< END	>> $ps
	$xmax	-14000	16  0   1  3	b) 
END
psbasemap -JX -R -Bnsew -K -O 			>> $ps

#psxy -JX -R -K -O -L -W6/255/0/0 	<<END>> $ps
#	160	-2000
#	290	-2000
#	290	1000
#	160	1000
#END

psxy -JX$graph_width/.72 -R$xmin/$xmax/0/1 -Y-.7 -K -N -O -M -W6/255/0/0t12_12:0 	<<END>> $ps
>
	130	0
	150	1
>
	285	0
	290	1
END





if ($switch_rheo == 0) exit


echo	-500	255	100	100	-80	200	0	0	B	> $model.paleta.strs.tmp
echo	-80	200	0	0	-0	0	0	0	B	>> $model.paleta.strs.tmp
echo	0	0	0	0	80	0	0	200	B	>> $model.paleta.strs.tmp
echo	80	0	0	230	400	130	130	255	B	>> $model.paleta.strs.tmp

echo	0	70	70	255	600	170	0	170	B	> $model.paleta.temp.tmp
echo	600	170	0	170	1200	255	0	0	B	>> $model.paleta.temp.tmp

echo	-1000				>	$model.contours1.z.tmp
echo	-300				>>	$model.contours1.z.tmp
echo	-100				>>	$model.contours1.z.tmp
echo	-30				>>	$model.contours1.z.tmp
echo	-10				>>	$model.contours1.z.tmp
echo	-3				>>	$model.contours1.z.tmp
echo	-1				>>	$model.contours1.z.tmp
echo	1				>>	$model.contours1.z.tmp
echo	3				>>	$model.contours1.z.tmp
echo	10				>>	$model.contours1.z.tmp
echo	30				>>	$model.contours1.z.tmp
echo	100				>>	$model.contours1.z.tmp
echo	300				>>	$model.contours1.z.tmp
echo	1000				>>	$model.contours1.z.tmp

#stress clip file:
awk '{if (substr($0,1,1) != "#") print $1, -$(NF-1)/1000}' $model.xzt 	> $model.stress.clip.tmp
awk '{if (substr($0,1,1) != "#") print $1, (-$(NF-1)+70000)/1000}' $model.xzt > $model.aux.tmp
invertfile $model.aux.tmp 			>> $model.stress.clip.tmp


#STRESS-EET:
surface	$model.strs -G$model.strs.bin -I2/1 -R$xmin/$xmax/-2/60 -H2 
psbasemap -JX$graph_width/-1.8 -R$xmin/$xmax/-2/60 -Ba50f10/20f10:"Depth (km)":nSeW \
	-Y-4.8 -K -O 										>> $ps
psclip	$model.stress.clip.tmp -JX -R -O -K 							>> $ps
grdimage	$model.strs.bin -C$model.paleta.strs.tmp -JX -R -O -K  				>> $ps
# for anotation: -G6/10 -A10f10/255
grdcontour	$model.strs.bin -JX -R -C$model.contours1.z.tmp -W3/0 -F0 -K -O 		>> $ps
psclip -S  -JX -R -O -K 									>> $ps
pstext	-JX	-R  -O 	-K -W0	-G255							<< END	>> $ps
	$xmax	59	16  0   1  3	d) 
END
psxy	$model.stress.clip.tmp -JX -R -O -W10 -K 						>> $ps
psxy $model.eet -JX -R$xmin/$xmax/-2000/60000 -O -W10/0t15_15:0 -K -H1 				>> $ps
psxy $model.eet -JX -R$xmin/$xmax/-2000/60000 -O -W10/255t15_15:15 -K -H1 			>> $ps
psbasemap -JX -R$xmin/$xmax/-2/60 -Bnsew -O -K							>> $ps

#psscale -C$model.paleta.strs.tmp -B:"Stress (MPa)": -D2.2/-.5/4/.2h -O -K			>> $ps


#TEMP-CRUST
#surface	$model.temp -G$model.temp.bin -I2/1 -R$xmin/$xmax/-5/60 -H2 
#psbasemap -JX$graph_width/-1.5 -R$xmin/$xmax/0/50 -Ba50:"Distance (km)":/20f10:"Depth (km)":NseW -Y7 -O -K	>> $ps
#psclip	$model.stress.clip.tmp -JX -R -O -K 							>> $ps
#grdimage	$model.temp.bin -C$model.paleta.temp.tmp -JX -R -O -K  				>> $ps
#grdcontour	$model.temp.bin -JX -R -C200 -A200f10 -W3/255 -K -O 				>> $ps
#if (-r $model.CRUST)  awk '{if (substr($1,1,1)!="#") print $1/1000, $2}' $model.CRUST \
#					| psxy  -JX -R$xmin/$xmax/0/50000 -W15/0 -N -O -K	>> $ps
#if (-r $model.UCRUST) awk '{if (substr($1,1,1)!="#") print $1/1000, $2}' $model.UCRUST \
#					| psxy  -JX -R -W15/0 -N -O -K 				>> $ps
#psclip -S  -JX -R -O -K 									>> $ps
#pstext	-JX	-R  -O 	-K -W0	-G255							<< END	>> $ps
#	$xmax	49000	16  0   1  3	a) 
#END
#psxy	$model.stress.clip.tmp -JX -R -O -W10 -K 						>> $ps
#psbasemap -JX$graph_width/-1.5 -R$xmin/$xmax/0/50 -Bnsew -O 					>> $ps

#psscale -C$model.paleta.temp.tmp -B:"Temperature (@+o@+C)": -D2.2/-.13/4/.2h -O		>> $ps


if (-r $model.xg) then 
	awk '{if (NR>=3) print $1, $2}' $model.xg \
		| psxy -JX$graph_width/2 -R$xmin/$xmax/-200/200 -W4/255/0/0 -Y7 -O -K \
		-Ba50f25g50:"Distance (km)":/100f50g100:"Gravity Anomaly (mGal)":nSeW\
		>> $ps
	awk '{if (NR>=3) print $1, $3}' $model.xg \
		| psxy -JX -R$xmin/$xmax/-20/20 -W4/0/255/0 -O -K \
		-B/10f5:"Geoid Height (m)":E \
		>> $ps
endif

pstext	-JX	-R  -O									<< END	>> $ps
END


rm -f   $model.*.tmp $model.strs.bin $model.temp.bin

