#!/bin/csh
##############################################################################
#	Job for tao graphic output with GMT
##############################################################################


set modelname	= topoinest
set xmin	= 0
set xmax	= 600
set ymin	= -4000
set ymax	= 4000
set numcols 	= `awk '(NR==4) {print NF}' $modelname.pfl`
set ps   	= topo_est_inest.ps
@ numhorizs 	= $numcols - 1 
@ col  		=  3
@ xminbasam 	= $xmin 
@ xmaxbasam 	= $xmax 
@ yminbasam 	= $ymin + 1


echo Number of horizons: $numhorizs
echo Output postscript:   $ps
echo Region: $xmin,$xmax / $ymin,$ymax

echo  $xmaxbasam $yminbasam > pru3.tmp
echo  $xminbasam $yminbasam >> pru3.tmp
awk   '{print $1, $2}' $modelname.pfl >> pru3.tmp
invertfile $modelname.pfl > pru2.tmp


cat pru2.tmp | awk '{print $1, $3}' | cat $modelname.pfl - | \
	psxy -JX7.5/3.75 -R$xmin/$xmax/$ymin/$ymax -Ba200f50:"(km)":/2000f1000g10000:Altitud\ \(m\):nSew \
		-F0/0/0 -K -Y5 -X11 -P > $ps
psxy pru3.tmp -JX -R -O -K -L -G130 >> $ps


while ($col <= $numcols)
	echo $col | \
		cat - $modelname.pfl | \
		awk '{if (NR==1) colawk=$1; else print $1, $colawk}' > pru.tmp
	@ colant = $col - 1
	echo $colant | \
		cat - pru2.tmp | \
		awk '{if (NR==1) colawk=$1; else print $1, $colawk}' >> pru.tmp

	@ Rcolor = ($col - 2) * 12 + 130
	@ Gcolor = ($col - 2) * 12 + 145 
	@ Bcolor = ($col - 2) * 9 + 60 
	psxy pru.tmp -JX -R -O -K -L -G$Rcolor/$Gcolor/$Bcolor >> $ps
	rm -f pru.tmp
	@ col++
end

@ xtitle = ($xmin + $xmax)/ 2
@ dy = ($ymax - $ymin)/ 10
@ dx = ($xmax - $xmin)/ 10
@ ytitle = $ymax + $dy
@ ybasam = $ymin + 1 * $dy
@ ytitlex = $ymin - $dy
@ ytitley = $ymin + 5 * $dy
@ xtitley = $xmin - ($dx / 2)
pstext -JX -R -O -K <<END>> $ps
	100	-2500 		11 0 1 2 	basamento
	360 	500 		17 0 12 2 	r
	369	500 		14 0 1 2 	@-i
	290 	-1500		11 0 1 2	c a r g a s
	380 	500		7  0 1 1	\(distintas densidades\)
	50	2200		18 0 1 2 	b\)
END


rm -f pru*.tmp








set modelname	= topoestable
set numcols 	= `awk '(NR==4) {print NF}' $modelname.pfl`
@ numhorizs 	= $numcols - 1 
@ col  		=  3

echo Number of horizons: $numhorizs
echo Output postscript:   $ps
echo Region: $xmin,$xmax / $ymin,$ymax

echo  $xmaxbasam $yminbasam > pru3.tmp
echo  $xminbasam $yminbasam >> pru3.tmp
awk   '{print $1, $2}' $modelname.pfl >> pru3.tmp
invertfile $modelname.pfl > pru2.tmp


cat pru2.tmp | awk '{print $1, $3}' | cat $modelname.pfl - | \
	psxy -JX -R$xmin/$xmax/$ymin/$ymax \
		-Ba200f50:"(km)":/2000f1000:Altitud\ \(m\):nSeW -F0/0/0 \
		-K -X-8 -O >> $ps

psxy pru3.tmp -JX -R -O -K -L -G130 >> $ps


while ($col <= $numcols)
	echo $col | \
		cat - $modelname.pfl | \
		awk '{if (NR==1) colawk=$1; else print $1, $colawk}' > pru.tmp
	@ colant = $col - 1
	echo $colant | \
		cat - pru2.tmp | \
		awk '{if (NR==1) colawk=$1; else print $1, $colawk}' >> pru.tmp

	@ Rcolor = ($col - 2) * 12 + 130
	@ Gcolor = ($col - 2) * 12 + 140 
	@ Bcolor = ($col - 2) * 10 + 60 
	psxy pru.tmp -JX -R -O -K -L -G$Rcolor/$Gcolor/$Bcolor >> $ps
	rm -f pru.tmp
	@ col++
end

@ xtitle = ($xmin + $xmax)/ 2
@ dy = ($ymax - $ymin)/ 10
@ dx = ($xmax - $xmin)/ 10
@ ytitle = $ymax + $dy
@ ybasam = $ymin + 1 * $dy
@ ytitlex = $ymin - $dy
@ ytitley = $ymin + 5 * $dy
@ xtitley = $xmin - ($dx / 2)
pstext -JX -R -O <<END>> $ps
	100	-2500 		11 0 1 2 	basamento
	300 	550 		11 0 12 2 	r
	308	550 		11 0 1 2 	@-c
	300 	-1500 		11 0 12 2 	r   .
	295	-1500 		9  0 1 1 	@-relleno
	230 	1800		11 0 1 2	carga
	50	2200		18 0 1 2 	a\)
END


rm -f pru*.tmp

