#!/bin/csh

set prj = sinus
set ps = 	comp_degree.results.ps
set densasthen = 3200
set denscrust = 2750
set horz_force = 0

set load_ampl = 1000
set Timefinal = (0 .5 1 2 5 7 10 14 20 25 30 40 45 50)
set Te =  (1 2e3 4e3 5e3 8e3 10e3 15e3 20e3 25e3 30e3 35e3 40e3 45e3 50e3 70e3 100e3 150e3)
set wl =  (50e3 100e3 200e3 500e3 1000e3)

cat - <<END> $prj.PRM
	version	tao v4.0
	Nx		1001 		Number of x points (distance axis).
	x0		-500e3		Left
	xf		+500e3		Right
	xmin		-300e3		Left
	xmax		+300e3		Right
	ymin		-2000		Bottom
	ymax		2000		Top
		
	densasthen	$densasthen
	denscrust	$denscrust
	
	isost_model	2		To switch the thinplate model of lithosphere:
	Te		10e3		Default Elastic Thickness (if no .EET file). Te=0 => local isostasy.
	boundary_conds	3		#0: Left edge is the center of a simmetric model and the plate is not broken there. Right edge is free.
	horz_force	$horz_force
	hydro_model	0
	erosed_model	0
	
	Timeini		0		Initial time.
	tau		1		Relaxation time (used only for the viscoelastic plate model).
	dt		1		Increment time.
		
	switch_sea	0		For existence of sea.
	switch_files	0		For extra file output.
	switch_ps	0		For postscript output.
END

#calculate local isostatic w0 (dependent only on load amplitude).
echo time 0 > $prj\1.UNIT
echo Calculating local isostatic deflection amplitude with wl = $wl[1]
awk -v wl=$wl[1] -v load_ampl=$load_ampl 'BEGIN{for (x=-500e3; x<=500e3; x+=1e3) print x, load_ampl*cos(2*3.1415927*x/wl)}' >> $prj\1.UNIT
tao $prj -tf0 -T1 -M1 -S > tmp.tmp
set w0_tao = `awk -v wl=$wl[1] '{if ($1==0) print -$2}' $prj.pfl`
set w0_theo = `awk -v densasthen=$densasthen -v densload=$denscrust -v load_ampl=$load_ampl 'BEGIN {print densload*load_ampl/densasthen}'`
echo w0_tao= $w0_tao  w0_theo= $w0_theo

if ($1 == C) then 
cp -f comp_degree.results.txt comp_degree.results.txt.bk
echo "#t/tau, Te, wavelength, C_tAo, C_theor " > comp_degree.results.txt
foreach k ($wl) 
	foreach j ($Te) 
		foreach i ($Timefinal) 
			echo $i"	"$j"	"$k 
			echo -n $i"	"$j"	"$k >> comp_degree.results.txt
			echo time 0 > $prj\1.UNIT
			awk -v wl=$k -v load_ampl=$load_ampl 'BEGIN{for (x=-500e3; x<=500e3; x+=1e3) print x, load_ampl*cos(2*3.1415927*x/wl)}' >> $prj\1.UNIT
			set td = `awk -v tdivtau=$i 'BEGIN{td = tdivtau/250; print td;}'`
			tao $prj -td$td -tf$i -T$j -S > tmp.tmp
			set Ctao  = `awk -v w0=$w0_tao '{if ($1==0) print -$2/w0}' $prj.pfl`
			set Ctheo = `awk -v Te=$j -v wl=$k -v tdivtau=$i -v densasthen=$densasthen -v horz_force=$horz_force -f comp_degree.awk`
			echo "	"$Ctao "	"$Ctheo[2] >> comp_degree.results.txt
		end
	end	
end
endif


cat - <<END>contours.tmp
	.9	A
	.7	C
	.5	A
	.3	C
	.1	A
END
psbasemap -JX11 -R0/50/0/100 -B:."Isost. compensation w.length=50,100,200 km (black,red,green)":a5f1:"t/tau":/20f10:"Te (km)":nSeW \
	-X2.5 -Y1.5 -P -K > $ps
awk '{if ($3==50e3)  print $1, $2/1e3, $5}' comp_degree.results.txt | \
	surface -R -Gresults.grd.tmp -I1/2 -T.0
grdcontour results.grd.tmp -JX -R -Ccontours.tmp -O -K -W2/0/0/0     -Af7 >> $ps
awk '{if ($3==100e3) print $1, $2/1e3, $5}' comp_degree.results.txt | \
	surface -R -Gresults.grd.tmp -I1/2 -T.0
grdcontour results.grd.tmp -JX -R -Ccontours.tmp -O -K -W3/225/0/0ta -Af7/255/40/40 >> $ps
awk '{if ($3==200e3) print $1, $2/1e3, $5}' comp_degree.results.txt | \
	surface -R -Gresults.grd.tmp -I1/2 -T.0
grdcontour results.grd.tmp -JX -R -Ccontours.tmp -O -K -W4/0/175/0to -Af7/0/255/0 >> $ps

psbasemap -JX11 -R0/60/0/1 -B:."wavelength=50,100,200 km (red,green,blue)":a10f5:"Te (km)":/a.2f.10:"Degree of isostatic compensation C":nSeW \
	-O -K -Y14 >> $ps
awk '{if ($3==50e3 && $1==0)  print $2/1e3, $5}' comp_degree.results.txt | \
	psxy -JX -R -W4/255/0/0 -O -K >> $ps
awk '{if ($3==100e3 && $1==0) print $2/1e3, $5}' comp_degree.results.txt | \
	psxy -JX -R -W4/0/255/0 -O -K >> $ps
awk '{if ($3==200e3 && $1==0) print $2/1e3, $5}' comp_degree.results.txt | \
	psxy -JX -R -W4/0/0/255 -O >> $ps

rm -f *.tmp


