#!/bin/csh

set project = forebu_trap_time
set ps = $project.ps

if ($1 == "C") then
tao $project -T10e3 -V | grep -E "Ma |deflection min. now" | \
	awk '{if (substr($0,1,1)=="T") {printf("%s", substr($0,3,5)); sign=1} else {if (sign==1) {printf("\t%s\t%s\n", $5, $10); sign=0}}}' |\
	awk '{print $3, -$2, $1}' > $project.T10.tao.out
tao $project -T20e3 -V | grep -E "Ma |deflection min. now" | \
	awk '{if (substr($0,1,1)=="T") {printf("%s", substr($0,3,5)); sign=1} else {if (sign==1) {printf("\t%s\t%s\n", $5, $10); sign=0}}}' |\
	awk '{print $3, -$2, $1}' > $project.T20.tao.out

mv $project\1.CRG $project\1.CRG.bk
tao $project -T10e3 -L0 -s1e12 -V | grep -E "Ma |deflection max. now" | \
	awk '{if (substr($0,1,1)=="T") {printf("%s", substr($0,3,5)); sign=1} else {if (sign==1) {printf("\t%s\t%s\n", $5, $10); sign=0}}}' |\
	awk '{print $3, $2, $1}' > $project.T10.puntual.tao.out
tao $project -T20e3 -L0 -s1e12 -V | grep -E "Ma |deflection max. now" | \
	awk '{if (substr($0,1,1)=="T") {printf("%s", substr($0,3,5)); sign=1} else {if (sign==1) {printf("\t%s\t%s\n", $5, $10); sign=0}}}' |\
	awk '{print $3, $2, $1}' > $project.T20.puntual.tao.out
mv $project\1.CRG.bk $project\1.CRG
endif

#CUÑA LOAD
psxy	$project.T10.tao.out -JX15/9 -R10/110/100/400 -B:"distancia al frente de la carga (km)":a20f5/:"altura del forebulge (m)":a50f10nWeS -W10 -X3 -Y3 -K -P >  $ps
awk '{if ($3%5 == 0) print $0}' $project.T10.tao.out | psxy -JX	-R  -St.2 -G255 -W8 -K -O	>>  $ps
psxy	$project.T20.tao.out -JX -R -W10 -K -O	>>  $ps
awk '{if ($3%5 == 0) print $0}' $project.T20.tao.out | psxy -JX	-R  -Sc.2 -G255 -W5 -K -O	>>  $ps

#POINT LOAD:
psxy	$project.T10.puntual.tao.out -JX -R -W6ta -O -K >>  $ps
awk '{if ($3%5 == 0) print $0}' $project.T10.puntual.tao.out | psxy -JX	-R -St.13 -G255 -W8 -K -O	>>  $ps
psxy	$project.T20.puntual.tao.out -JX -R -W6ta -K -O	>>  $ps
awk '{if ($3%5 == 0) print $0}' $project.T20.puntual.tao.out | psxy -JX	-R -Sc.13 -G255 -W5 -K -O	>>  $ps

awk '{if ($3==0) auxtxt="Ma"; else auxtxt=""; if ($3%10 == 0) printf("%f %f %d %d %d %d\t%.0f %s\n", $1+.5, $2+3, 6, 0, 0, 3, $3, auxtxt);}' $project.T*.tao.out \
	| pstext -JX -R -O -K	>>  $ps


pstext	-JX	-R	-O	<< END	>>  $ps
#50	210	14  0  1  2		placa viscoelastica: evolucion del forebulge, carga trapezoidal (tau=5 Ma)
48	260	14  0  1  3		Te=10 km
85	240	14  0  1  3		Te=20 km
END

rm -f *.tmp
