
psxy	forebuendtime10.xy	-JX5/3	-R10/100/0/500	  -Ba20f10/100f20nWeS -W12 -M -V -X1 -Y1 -K -P > forebuendtime.ps
psxy	forebuendtime15.xy	-JX	-R  			-W12 -M 	-V -K -O		>>  forebuendtime.ps
#psxy	foreburecttime15.txt	-JX	-R  			-W6  -M 	-V -K -O		>>  forebuendtime.ps
#psxy	foreburecttime15.txt	-JX	-R  			-W6  -M 	-V -K -O		>>  forebuendtime.ps
psxy	forebuendtime10.simbol	-JX	-R  	-St.12 -M 	-W8	-K -V -O		>>  forebuendtime.ps
psxy	forebuendtime15.simbol	-JX	-R  	-Sc.12 -M 	-W5	-K -V -O		>>  forebuendtime.ps
pstext			-JX	-R	-Y.13				-K-V  -O		<< END	>>  forebuendtime.ps
55	570	17  0  1  2		Modelo viscoelastico: evolucion del forebulge 
55	520	15  0  1  2		producido por una fuerza vertical de 10@+12@+N/m ;  @~t@~=1Ma
50	-100	13  0  1  2		Distancia desde el limite de placa (km)
2	240	13  90 1  2		Altitud maxima del basamento (m)
40	230	15  0  1  3		E.T.=10 km
90	180	15  0  1  3		E.T.=15 km
END

pstext	forebuendtime10.simbol	-JX	-R	-X-.2	 -Y-.3		-V  -K -O		>>  forebuendtime.ps
pstext	forebuendtime15.simbol	-JX	-R	-X.3	 -Y+.25		-V  -O			>>  forebuendtime.ps
