# los ficheros *.out son resultados del modelo para 1-5e12 N/m de fuerza de contorno en
# un caso de placa rota y otro de continua. EEE=10Km. 

psxy CCcont0.out	-JX2.4/1.5185	-R0/150/-6000/1900	-Ba20f5:Distancia\ \(km\):/2000f500:Deflexion\ \(m\):NW	-W4 -X1.8 -Y4 -V -K -P	> CCcont.ps
psxy CCcont1.out	-JX	-R	-W4 -V -O -K	>> CCcont.ps
psxy CCcont2.out	-JX	-R	-W4 -V -O -K	>> CCcont.ps
psxy CCcont3.out	-JX	-R	-W4 -V -O -K	>> CCcont.ps
psxy CCcont4.out	-JX	-R	-W4 -V -O -K	>> CCcont.ps
psxy		-JX	-R	-W2 -V -O -K	<< END>> CCcont.ps
0	0
100	0
200	0
END
pstext 		-JX	-R	-V -O -K	<< END>> CCcont.ps
80	-3000	15  0  1  2	Semi-placa
80	-3900	15  0  1  2	 continua
5	-800	10  0  1  1	1 TN/m
5	-1700	10  0  1  1	2 
5	-2700	10  0  1  1	3 
5	-3700	10  0  1  1	4 
5	-4700	10  0  1  1	5 TN/m
90	600	10  0  1  1	F
END


psxy CCrota0.out	-JX2.4/3	-R0/150/-10000/1900	-Ba20f5:Distancia\ \(km\):/2000f500NW	 -X2.8 -Y-1.48 -W4 -V -O -K	>> CCcont.ps
psxy CCrota1.out	-JX	-R	-W4 -V -O -K	>> CCcont.ps
psxy CCrota2.out	-JX	-R	-W4 -V -O -K	>> CCcont.ps
psxy CCrota3.out	-JX	-R	-W4 -V -O -K	>> CCcont.ps
psxy CCrota4.out	-JX	-R	-W4 -V -O -K	>> CCcont.ps
psxy		-JX	-R	-W2 -V -O -K	<< END>> CCcont.ps
0	0
100	0
200	0
END
pstext 		-JX	-R	-V -O	<< END>> CCcont.ps
-15	6000	18  0  1  2	Efecto de la variacion de las condiciones de contorno.
-15	5000	18  0  1  2	E.E.E.=10 Km
80	-4000	15  0  1  2	Limite de placa
4	-1400	10  0  1  1	1 TN/m
4	-3200	10  0  1  1	2 
4	-5100	10  0  1  1	3 
4	-7100	10  0  1  1	4 
4	-9300	10  0  1  1	5 TN/m
70	1100	10  0  1  1	F
END


