#!/bin/csh
##############################################################################
#	Job for tao graphic output with GMT
##############################################################################
#Syntax:  tao.gmt.job <modelname> <xmin> <xmax> <ymin> <ymax> 


set modelname	= $argv[1]
set xmin	= $2
set xmax	= $3
set ymin	= $4
set ymax	= $5
set numcols 	= `awk '(NR==4) {print NF}' $modelname.pfl`
set ps   	= $modelname.gmt.ps
@ numhorizs 	= $numcols - 1 
@ col  		=  3
@ xminbasam 	= $xmin 
@ xmaxbasam 	= $xmax 
@ yminbasam 	= $ymin + 1


#set verbose
#set echo

echo Number of horizons: $numhorizs
echo Output postscript:   $ps
echo Region: $xmin,$xmax / $ymin,$ymax

echo  $xmaxbasam $yminbasam > pru3.tmp
echo  $xminbasam $yminbasam >> pru3.tmp
awk   '{print $1, $2}' $modelname.pfl >> pru3.tmp
invertfile $modelname.pfl > pru2.tmp

#fondo azul:
#psxy -JX12/8.5 -R1/2/1/2 -K -L -G0/0/100 -X0 -Y0 << END > $ps
#	1.001	1
#	1.001	2
#	2 	2
#	2 	1
#END

cat pru2.tmp | awk '{print $1, $3}' | cat $modelname.pfl - | \
	psxy -JX9/3 -R$xmin/$xmax/$ymin/$ymax -Ba100f25:Distancia\ \(km\):/2000f1000:Altitud\ \(m\):nSeW -F0/0/0 -K -Y2 -X1.6 > $ps

psxy pru3.tmp -JX -R -O -K -L -G80 >> $ps


while ($col <= $numcols)
	echo $col | \
		cat - $modelname.pfl | \
		awk '{if (NR==1) colawk=$1; else print $1, $colawk}' > pru.tmp
	@ colant = $col - 1
	echo $colant | \
		cat - pru2.tmp | \
		awk '{if (NR==1) colawk=$1; else print $1, $colawk}' >> pru.tmp

	@ Rcolor = ($col - 2) * 22 + 120
	@ Gcolor = ($col - 2) * 22 + 105 
	@ Bcolor = ($col - 2) * 4 + 30 
	psxy pru.tmp -JX -R -O -K -L -G$Rcolor/$Gcolor/$Bcolor >> $ps
	rm -f pru.tmp
	@ col++
end

@ xtitle = ($xmin + $xmax)/ 2
@ dy = ($ymax - $ymin)/ 10
@ dx = ($xmax - $xmin)/ 10
@ ytitle = $ymax + $dy
@ ybasam = $ymin + 1 * $dy
@ ytitlex = $ymin - $dy
@ ytitley = $ymin + 5 * $dy
@ xtitley = $xmin - ($dx / 2)
psxy -JX -R -O -K -W6/255 -Sv <<END>> $ps
	255	0	-90	.6
	740	0	-90	.85
END
psxy -JX -R -O -K -W6 -Sv <<END>> $ps
	200	1800	0	5.3
END
pstext -JX -R -O -W <<END>> $ps
	750 1100		22 0 5 2	C = 0.9
	250 1100		22 0 5 2	C = 0.6
	750 2200		22 0 5 2	Te = 1 km
	250 2200		22 0 5 2	Te = 10 km
END


rm -f pru*.tmp
