#Te = 30 km
set ps = Fx.ps

set tecforce = 10
set xmax = 	1000e3

set vertforce = 2.6
set densamb = 	1000

psbasemap   -JX12.5/-3.75 -R0/400/-1/4 -Ba50f10/a1f.25g100:"deflexi\360n (km)":seW -K -X4 -Y12.5 -P > $ps
tao -Q -T30e3 -d1e3 -R$xmax -p$tecforce\e12 -s$vertforce\e12 -ra$densamb > Ptest.tmp
tao -Q -T30e3 -d1e3 -R$xmax -p-$tecforce\e12 -s$vertforce\e12 -ra$densamb | invertfile >> Ptest.tmp
psxy Ptest.tmp -JX12.5/3.75 -R0/400/-4000/1000 -G200 -L -W1 -O -K >> $ps
tao -Q -T30e3 -d1e3 -R$xmax -p0 -s$vertforce\e12 -ra$densamb | \
	psxy -JX -R -M -W7 -O -K >> $ps


pstext	-JX -R -O -N -K << END >> $ps
#	200	2900	14 0.0 1 2  Efecto de una fuerza tect\360nica horizontal
#	200	2200	14 0.0 1 2  de -1 a +1 TN/m
	5	-650	11 0.0 1 1  Agua
	397	-3800	11 0.0 1 3  F@-z@- = $vertforce TN/m      a)
	50	-3600	11 0.0 1 1  |F@-x@-| < $tecforce TN/m
END
psxy -JX -R -W2 -O -K <<END>> $ps
	50	-3400
	10	-3000
END


set vertforce = 1.3
set densamb = 	2400

psbasemap  -JX12.5/-3.75 -R0/400/-1/4 -Ba50f10:"distancia (km)":/a1f.25g100:"deflexi\360n (km)":SeW -Y-4.25 -O -K >> $ps
tao -Q -T30e3 -d1e3 -R$xmax -p$tecforce\e12 -s$vertforce\e12 -ra$densamb > Ptest.tmp
tao -Q -T30e3 -d1e3 -R$xmax -p-$tecforce\e12 -s$vertforce\e12 -ra$densamb | invertfile >> Ptest.tmp
psxy Ptest.tmp -JX12.5/3.75 -R0/400/-4000/1000 -G200 -L -W1 -O -K >> $ps
tao -Q -T30e3 -d1e3 -R$xmax -p0 -s$vertforce\e12 -ra$densamb | \
	psxy -JX -R -M -W7 -O -K >> $ps

pstext	-JX -R -O -K << END >> $ps
	5	-650	11 0.0 1 1  Sedimentos
	397	-3800	11 0.0 1 3  F@-z@- = $vertforce TN/m      b)
	50	-3600	11 0.0 1 1  |F@-x@-| < $tecforce TN/m
END
psxy -JX -R -W2 -O <<END>> $ps
	50	-3400
	20	-3000
END


rm -f Ptest*tmp
